#This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# For deployment, it will be necessary to create a PyPI API token and store it as a secret
# https://docs.github.com/en/actions/reference/encrypted-secrets

name: Auto-convert Nipype tasks to Pydra

on:
    workflow_dispatch: # Trigger this workflow manually or via a repository dispatch event
    repository_dispatch:
        types: [auto-conv]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  auto-conv:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout auto-conv branch
      run: git checkout auto-conv

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build dependencies
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: python -m pip install -r ./nipype-auto-conv/requirements.txt

    - name: Run automatic Nipype > Pydra conversion
      run: ./nipype-auto-conv/generate

    - name: Create branch that rebases main on auto-conv
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git checkout -b main-rebase main
        git rebase auto-conv

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: main-rebase
        title: 'Rebase main on auto-conv'
        body: 'This PR rebases the main branch on the auto-conv branch to include the latest Nipype to Pydra conversions.'
        base: main
        commit-message: 'Rebase main on auto-conv'
        labels: auto-conv

    - uses: actions/upload-artifact@v4
      with:
        name: converted-nipype
        path: pydra/tasks/ants/v2
        retention-days: 7
